### ISSUE TITLE
报语法错误

### ISSUE THREAD

**Issue by TRHX** [coder-fly/geetest_reverse#1]
运行test.py，错误如下，是啥原因导致的？

```pyhon
Traceback (most recent call last):
  File "D:/python3Project/SpiderTest/geetest_reverse-main/test/test.py", line 9, in <module>
    resp = geetest.validate("7e4fe1f3a3ebfec6e4af84f8090cdbbe", "127.0.0.1")
  File "D:\python3Project\SpiderTest\geetest_reverse-main\validate.py", line 159, in validate
    challenge, new_challenge, gap_position = self.get_img_track(gt, ip)
  File "D:\python3Project\SpiderTest\geetest_reverse-main\validate.py", line 41, in get_img_track
    base_data = self.ctx_sense.call("stringify", base_data)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\execjs\_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\execjs\_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\execjs\_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\execjs\_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: SyntaxError: 语法错误
```

**Comment by coder-fly** [comment]
是否是使用的node.js作为execjs的js引擎？

**Comment by TRHX** [comment]
已解决，添加了引擎设置为 node.js
